apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-secret-syncer
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list", "update"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-secret-syncer
subjects:
- kind: ServiceAccount
  name: cert-secret-syncer
roleRef:
  kind: Role
  name: cert-secret-syncer
  apiGroup: rbac.authorization.k8s.io
