apiVersion: rbac.authorization.k8s.io/v1
kind: {{if .Values.clusterRBAC}}Cluster{{end}}Role
metadata:
  name: {{ include "..serviceAccountName" . }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list", "update"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "watch", "list", "update"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: {{if .Values.clusterRBAC}}Cluster{{end}}RoleBinding
metadata:
  name: {{ include "..serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "..serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: {{if .Values.clusterRBAC}}Cluster{{end}}Role
  name: {{ include "..serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
